/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VokabelnIndexRouteImport } from './routes/vokabeln/index'
import { Route as ThemenIndexRouteImport } from './routes/themen/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as PruefungIndexRouteImport } from './routes/pruefung/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as GrammatikIndexRouteImport } from './routes/grammatik/index'
import { Route as VokabelnIdIndexRouteImport } from './routes/vokabeln/$id/index'
import { Route as PruefungLevelIndexRouteImport } from './routes/pruefung/$level/index'
import { Route as VokabelnIdTopicIdIndexRouteImport } from './routes/vokabeln/$id/$topicId/index'
import { Route as PruefungLevelModelltestsIndexRouteImport } from './routes/pruefung/$level/modelltests/index'
import { Route as PruefungLevelModuleIndexRouteImport } from './routes/pruefung/$level/$module/index'
import { Route as GrammatikSectionTopicIdIndexRouteImport } from './routes/grammatik/$section/$topicId/index'
import { Route as QuizLevelSkillTestIdIndexRouteImport } from './routes/quiz/$level/$skill/$testId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VokabelnIndexRoute = VokabelnIndexRouteImport.update({
  id: '/vokabeln/',
  path: '/vokabeln/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemenIndexRoute = ThemenIndexRouteImport.update({
  id: '/themen/',
  path: '/themen/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const PruefungIndexRoute = PruefungIndexRouteImport.update({
  id: '/pruefung/',
  path: '/pruefung/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammatikIndexRoute = GrammatikIndexRouteImport.update({
  id: '/grammatik/',
  path: '/grammatik/',
  getParentRoute: () => rootRouteImport,
} as any)
const VokabelnIdIndexRoute = VokabelnIdIndexRouteImport.update({
  id: '/vokabeln/$id/',
  path: '/vokabeln/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PruefungLevelIndexRoute = PruefungLevelIndexRouteImport.update({
  id: '/pruefung/$level/',
  path: '/pruefung/$level/',
  getParentRoute: () => rootRouteImport,
} as any)
const VokabelnIdTopicIdIndexRoute = VokabelnIdTopicIdIndexRouteImport.update({
  id: '/vokabeln/$id/$topicId/',
  path: '/vokabeln/$id/$topicId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PruefungLevelModelltestsIndexRoute =
  PruefungLevelModelltestsIndexRouteImport.update({
    id: '/pruefung/$level/modelltests/',
    path: '/pruefung/$level/modelltests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PruefungLevelModuleIndexRoute =
  PruefungLevelModuleIndexRouteImport.update({
    id: '/pruefung/$level/$module/',
    path: '/pruefung/$level/$module/',
    getParentRoute: () => rootRouteImport,
  } as any)
const GrammatikSectionTopicIdIndexRoute =
  GrammatikSectionTopicIdIndexRouteImport.update({
    id: '/grammatik/$section/$topicId/',
    path: '/grammatik/$section/$topicId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuizLevelSkillTestIdIndexRoute =
  QuizLevelSkillTestIdIndexRouteImport.update({
    id: '/quiz/$level/$skill/$testId/',
    path: '/quiz/$level/$skill/$testId/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grammatik/': typeof GrammatikIndexRoute
  '/login/': typeof LoginIndexRoute
  '/pruefung/': typeof PruefungIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/themen/': typeof ThemenIndexRoute
  '/vokabeln/': typeof VokabelnIndexRoute
  '/pruefung/$level/': typeof PruefungLevelIndexRoute
  '/vokabeln/$id/': typeof VokabelnIdIndexRoute
  '/grammatik/$section/$topicId/': typeof GrammatikSectionTopicIdIndexRoute
  '/pruefung/$level/$module/': typeof PruefungLevelModuleIndexRoute
  '/pruefung/$level/modelltests/': typeof PruefungLevelModelltestsIndexRoute
  '/vokabeln/$id/$topicId/': typeof VokabelnIdTopicIdIndexRoute
  '/quiz/$level/$skill/$testId/': typeof QuizLevelSkillTestIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grammatik': typeof GrammatikIndexRoute
  '/login': typeof LoginIndexRoute
  '/pruefung': typeof PruefungIndexRoute
  '/register': typeof RegisterIndexRoute
  '/themen': typeof ThemenIndexRoute
  '/vokabeln': typeof VokabelnIndexRoute
  '/pruefung/$level': typeof PruefungLevelIndexRoute
  '/vokabeln/$id': typeof VokabelnIdIndexRoute
  '/grammatik/$section/$topicId': typeof GrammatikSectionTopicIdIndexRoute
  '/pruefung/$level/$module': typeof PruefungLevelModuleIndexRoute
  '/pruefung/$level/modelltests': typeof PruefungLevelModelltestsIndexRoute
  '/vokabeln/$id/$topicId': typeof VokabelnIdTopicIdIndexRoute
  '/quiz/$level/$skill/$testId': typeof QuizLevelSkillTestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grammatik/': typeof GrammatikIndexRoute
  '/login/': typeof LoginIndexRoute
  '/pruefung/': typeof PruefungIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/themen/': typeof ThemenIndexRoute
  '/vokabeln/': typeof VokabelnIndexRoute
  '/pruefung/$level/': typeof PruefungLevelIndexRoute
  '/vokabeln/$id/': typeof VokabelnIdIndexRoute
  '/grammatik/$section/$topicId/': typeof GrammatikSectionTopicIdIndexRoute
  '/pruefung/$level/$module/': typeof PruefungLevelModuleIndexRoute
  '/pruefung/$level/modelltests/': typeof PruefungLevelModelltestsIndexRoute
  '/vokabeln/$id/$topicId/': typeof VokabelnIdTopicIdIndexRoute
  '/quiz/$level/$skill/$testId/': typeof QuizLevelSkillTestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grammatik/'
    | '/login/'
    | '/pruefung/'
    | '/register/'
    | '/themen/'
    | '/vokabeln/'
    | '/pruefung/$level/'
    | '/vokabeln/$id/'
    | '/grammatik/$section/$topicId/'
    | '/pruefung/$level/$module/'
    | '/pruefung/$level/modelltests/'
    | '/vokabeln/$id/$topicId/'
    | '/quiz/$level/$skill/$testId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/grammatik'
    | '/login'
    | '/pruefung'
    | '/register'
    | '/themen'
    | '/vokabeln'
    | '/pruefung/$level'
    | '/vokabeln/$id'
    | '/grammatik/$section/$topicId'
    | '/pruefung/$level/$module'
    | '/pruefung/$level/modelltests'
    | '/vokabeln/$id/$topicId'
    | '/quiz/$level/$skill/$testId'
  id:
    | '__root__'
    | '/'
    | '/grammatik/'
    | '/login/'
    | '/pruefung/'
    | '/register/'
    | '/themen/'
    | '/vokabeln/'
    | '/pruefung/$level/'
    | '/vokabeln/$id/'
    | '/grammatik/$section/$topicId/'
    | '/pruefung/$level/$module/'
    | '/pruefung/$level/modelltests/'
    | '/vokabeln/$id/$topicId/'
    | '/quiz/$level/$skill/$testId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GrammatikIndexRoute: typeof GrammatikIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PruefungIndexRoute: typeof PruefungIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ThemenIndexRoute: typeof ThemenIndexRoute
  VokabelnIndexRoute: typeof VokabelnIndexRoute
  PruefungLevelIndexRoute: typeof PruefungLevelIndexRoute
  VokabelnIdIndexRoute: typeof VokabelnIdIndexRoute
  GrammatikSectionTopicIdIndexRoute: typeof GrammatikSectionTopicIdIndexRoute
  PruefungLevelModuleIndexRoute: typeof PruefungLevelModuleIndexRoute
  PruefungLevelModelltestsIndexRoute: typeof PruefungLevelModelltestsIndexRoute
  VokabelnIdTopicIdIndexRoute: typeof VokabelnIdTopicIdIndexRoute
  QuizLevelSkillTestIdIndexRoute: typeof QuizLevelSkillTestIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vokabeln/': {
      id: '/vokabeln/'
      path: '/vokabeln'
      fullPath: '/vokabeln/'
      preLoaderRoute: typeof VokabelnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themen/': {
      id: '/themen/'
      path: '/themen'
      fullPath: '/themen/'
      preLoaderRoute: typeof ThemenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pruefung/': {
      id: '/pruefung/'
      path: '/pruefung'
      fullPath: '/pruefung/'
      preLoaderRoute: typeof PruefungIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammatik/': {
      id: '/grammatik/'
      path: '/grammatik'
      fullPath: '/grammatik/'
      preLoaderRoute: typeof GrammatikIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vokabeln/$id/': {
      id: '/vokabeln/$id/'
      path: '/vokabeln/$id'
      fullPath: '/vokabeln/$id/'
      preLoaderRoute: typeof VokabelnIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pruefung/$level/': {
      id: '/pruefung/$level/'
      path: '/pruefung/$level'
      fullPath: '/pruefung/$level/'
      preLoaderRoute: typeof PruefungLevelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vokabeln/$id/$topicId/': {
      id: '/vokabeln/$id/$topicId/'
      path: '/vokabeln/$id/$topicId'
      fullPath: '/vokabeln/$id/$topicId/'
      preLoaderRoute: typeof VokabelnIdTopicIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pruefung/$level/modelltests/': {
      id: '/pruefung/$level/modelltests/'
      path: '/pruefung/$level/modelltests'
      fullPath: '/pruefung/$level/modelltests/'
      preLoaderRoute: typeof PruefungLevelModelltestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pruefung/$level/$module/': {
      id: '/pruefung/$level/$module/'
      path: '/pruefung/$level/$module'
      fullPath: '/pruefung/$level/$module/'
      preLoaderRoute: typeof PruefungLevelModuleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammatik/$section/$topicId/': {
      id: '/grammatik/$section/$topicId/'
      path: '/grammatik/$section/$topicId'
      fullPath: '/grammatik/$section/$topicId/'
      preLoaderRoute: typeof GrammatikSectionTopicIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$level/$skill/$testId/': {
      id: '/quiz/$level/$skill/$testId/'
      path: '/quiz/$level/$skill/$testId'
      fullPath: '/quiz/$level/$skill/$testId/'
      preLoaderRoute: typeof QuizLevelSkillTestIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GrammatikIndexRoute: GrammatikIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  PruefungIndexRoute: PruefungIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ThemenIndexRoute: ThemenIndexRoute,
  VokabelnIndexRoute: VokabelnIndexRoute,
  PruefungLevelIndexRoute: PruefungLevelIndexRoute,
  VokabelnIdIndexRoute: VokabelnIdIndexRoute,
  GrammatikSectionTopicIdIndexRoute: GrammatikSectionTopicIdIndexRoute,
  PruefungLevelModuleIndexRoute: PruefungLevelModuleIndexRoute,
  PruefungLevelModelltestsIndexRoute: PruefungLevelModelltestsIndexRoute,
  VokabelnIdTopicIdIndexRoute: VokabelnIdTopicIdIndexRoute,
  QuizLevelSkillTestIdIndexRoute: QuizLevelSkillTestIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
